paths:
  raw_data_path: '../Churn_Modelling.csv'
  output_dir: 'churn_preprocessing'
  artifact_dir: 'artifacts'

params:
  test_size: 0.2
  random_state: 42

features:
  drop_columns:
    - 'RowNumber'
    - 'CustomerId'
    - 'Surname'
  target_column: 'Exited'
  skewed_columns: []
  categorical_columns:
    - 'Geography'
    - 'Gender'
  scaling_columns:
    - 'CreditScore'
    - 'Age'
    - 'Tenure'
    - 'Balance'
    - 'NumOfProducts'
    - 'EstimatedSalary'
